version: "3"

tasks:
  run:
    desc: Assemble and run a nova program
    example: task run INPUT=./programs/main.nova OUTPUT=./bin/program.bin DEBUG=true
    silent: true
    vars:
      INPUT: "{{.INPUT}}"
      OUTPUT: "{{.OUTPUT}}"
      DEBUG_FLAG: '{{if eq .DEBUG "true"}}--debug{{end}}'
    cmds:
      - cd assembler && go run ./cmd/assembler/main.go -input ../{{.INPUT}} -output ../{{.OUTPUT}} {{.DEBUG_FLAG}}
      - gcc -Ivm/include -Ivm/include/kernel vm/src/*.c vm/src/kernel/*.c -o _run_temp
      - ./_run_temp {{.OUTPUT}} {{.DEBUG_FLAG}}
