version: "3"

tasks:
  run:
    silent: true
    cmds:
      - python3 assembler/nova.py
      - gcc -Iinclude src/*.c src/kernel/*.c -o _run_temp
      - ./_run_temp

  crun:
    desc: Launches the processor
    cmds:
      - gcc -Iinclude src/*.c src/kernel/*.c -o _run_temp
      - ./_run_temp
